In [1]:
import numpy as np
from Solver import Solver

In [2]:
Solver.solveUsingCG()


solved MILP using CG algorithm


In [3]:
Solver.solveMILP(1,2)

1
2
solved using MILP


In [3]:
x=np.array([[7,3,8],[7,3,8]])


3
[[7 3 8]
 [7 3 8]]
solved using MILP


In [2]:
tasks_table_6=np.array([
    [7,4,8,6,9,2,1,5,3],
    [0.96,1.07,0.8,1.43,0.95,0.98,0.77,1.08,1.6],
    [5,3,5,3,2,4,3,5,4],
    [6,10,12,5,13,5,5,8,6],
    [9,15,11,18,20,3,8,1,6],
    [40,32,39,18,31,24,19,32,9],
    [43,26,22,31,33,16,43,38,22],
    [79,182,38,124,62,173,80,83,168],
    [0,0,0,0,0,0,0,0,12],
    [195,195,190,195,195,195,195,195,195]
    ]
)


In [5]:
parameters=np.array([9,194,5.6,3.6,0.9,75/100])


In [6]:
Solver.solveMILP(parameters, tasks_table_6)


9
[[  7.     4.     8.     6.     9.     2.     1.     5.     3.  ]
 [  0.96   1.07   0.8    1.43   0.95   0.98   0.77   1.08   1.6 ]
 [  5.     3.     5.     3.     2.     4.     3.     5.     4.  ]
 [  6.    10.    12.     5.    13.     5.     5.     8.     6.  ]
 [  9.    15.    11.    18.    20.     3.     8.     1.     6.  ]
 [ 40.    32.    39.    18.    31.    24.    19.    32.     9.  ]
 [ 43.    26.    22.    31.    33.    16.    43.    38.    22.  ]
 [ 79.   182.    38.   124.    62.   173.    80.    83.   168.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.    12.  ]
 [195.   195.   190.   195.   195.   195.   195.   195.   195.  ]]
solved using MILP


In [12]:
q=tasks_table_6[1]


In [13]:
q


array([0.96, 1.07, 0.8 , 1.43, 0.95, 0.98, 0.77, 1.08, 1.6 ])